apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.labels.app }}  
  name: {{ .Values.labels.app }} 
spec:
  ports:
  - port: {{ .Values.service.ports }} 
    protocol: {{ .Values.service.protocol }} 
    targetPort: {{ .Values.service.ports }} 
  selector:
    app: {{ .Values.labels.app }} 
  type: {{ .Values.service.type }} 
